template_version = 1

[metadata]
name = "aztec-template"

[privacy]
recipient_private = true
amount_private = true
sender_private = true
memo_private = false

[runtime]
l1_chain_id = 31337
l2_chain_id = 31337
escape_timeout_blocks = 1200
default_gas_limit = 2000000

[addresses]
l1_portal = "0x0000000000000000000000000000000000000000"
protocol_contract = "0x0000000000000000000000000000000000000000"
token_address = "0x0000000000000000000000000000000000000000"

[modules]
enable_borrow = false
enable_repay = false
enable_lp = false
enable_queue = false
enable_yield = false
