[metadata]
name = "lido"

[privacy]
amount_private = false

[runtime]
escape_timeout_blocks = 1500

[addresses]
protocol_contract = "0xD000000000000000000000000000000000000000"

[modules]
enable_borrow = false
enable_repay = false
enable_lp = false
enable_queue = false
enable_yield = false
