[metadata]
name = "uniswap"

[privacy]
recipient_private = false

[runtime]
default_gas_limit = 3500000

[addresses]
protocol_contract = "0xC000000000000000000000000000000000000000"

[modules]
enable_borrow = false
enable_repay = false
enable_lp = false
enable_queue = false
enable_yield = false
